spring:
  mvc:
    view:
      prefix:  /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ecommerce201707b
    username: postgres
    password: postgres
      
server:
  context-path: /cheese